services:
  agent:
    build: .
    restart: always

    labels:
      traefik.enable: true
      traefik.http.services.doc-svc.loadbalancer.server.port: 8002
      traefik.http.routers.doc-rtr.rule: Host("doc.ai-adesso.de")
      traefik.http.routers.doc-rtr.service: doc-svc
      traefik.http.routers.doc-rtr.entrypoints: https

    volumes:
      - ./data:/data
      - ./logs:/logs

    ports:
      - "8002:8002"
    networks:
      - web

networks:
  web:
    name: traefik_web
    external: true
